name: Review & Deploy
on: 
  workflow_dispatch
jobs:
  review:
    name: Test the build
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Hello testing
        run: |
          echo "------------Test---------------"
          echo "$AWS_REGION"

  deploy:
    name: Deploy To stg
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Hello Staging
        run: |
          echo "------------Deploy---------------"
          echo "$AWS_REGION"
